### ISSUE TITLE
The Google Docs page for the installation instructions says access denied.

### ISSUE THREAD

**Issue by aryan-02** [PACTF/pactf-web2#20]
The Google Docs document that contains the instructions for installing and running PACTF starting from a fresh server (https://docs.google.com/document/d/1O-HpONG-if3xE7YQqYMVFYkE4mwYZmL-9rpbEDD16M0/edit?usp=sharing) says I need permission.

**Comment by aryan-02** [comment]
@yatharth 
@Reichenbachian 
Please help provide me with the setup instructions :)

**Comment by CT075** [comment]
I'm going to wait for one of the current maintainers to respond or give me the OK, but I have a copy of the document from when we were setting up the first time if necessary; from what it looks like the instructions aren't much different but there's probably less cleaning up to do.

**Comment by yatharth** [comment]
Hi @aryan-02,

Happy to help!

For background, could you let us know what you're trying to do/explore?

**Comment by aryan-02** [comment]
Hi @yatharth 
I'm planning to organise a small scale CTF contest for my school's computer club. So I need to modify and host the PACTF code onto a server, for which I need the documentation for installation...

**Comment by yatharth** [comment]
@aryan-02 Sounds great! Here is the document: [Deployment Instructions](https://docs.google.com/document/d/1O-HpONG-if3xE7YQqYMVFYkE4mwYZmL-9rpbEDD16M0/edit?usp=sharing).

**Comment by milesmcc** [comment]
Marking as closed, as the document appears to be what you're looking for. Feel free to ping me if you have any additional questions or would like to reopen the issue.
